<?php
session_start();
// include('def.php');  
include('sqlc.php'); //connect Db


// Get all Details 
$email=$_POST['user_email'];
$name=$_POST['user_name'];
$gender=$_POST['gender'];
$city=$_POST['city'];
$password=$_POST['pass'];
$mobile=$_POST['mobile'];
// Validate Data
if(!is_numeric($mobile))
{
echo "<h1>Mobile No. is not Correct</h1>";
exit;
}
if($name==''||$email==''||$city==''||$password=='')
{
echo "<h1>Please go Back annd fill form properly</h1>";
exit;
}
// Database adding
function add_data(&$email,&$city,&$gender,&$name,&$password,&$mobile)
{
$sql="INSERT INTO ads(email,city,gender,username,pass,mobile) VALUES ('$email','$city','$gender','$name','$password','$mobile')";

if(!mysql_query($sql))
{
echo mysql_error();
exit;
}
Header("Location:postadstep2.php?data=$processcode &email=$email");
$_SESSION['adname']=$adname;
}

function checkdata($email)
{
$sql="SELECT * from ads where email='$email'";
if($qr=mysql_query($sql))
echo "done";
$t=mysql_num_rows($qr);
if($t>=1)
{
echo 'You are already Registered , Please <a href="login.html">SignIn</a>';
exit;
}
}
function verifymail($email)
{
$sender="verify@site.com";
$subject="Verification of email";
$msg="Hi,
Thank you for signing up on.
Please verify your email address and start advertising your products for free.
please click here or copy paste url into browser


please donot reply to this email , it is autogenerated email.
";
mail();
echo 'A Verification mail has been sended to your email. please verify your mail to proceed';
}

$processcode=rand();
checkdata($email);
add_data($email,$city,$gender,$name,$password,$mobile);
verifymail($email)
?>